
export const PROFILE_UPDATED = "PROFILE_UPDATED";
export const PROFILE_CHANGE = "PROFILE_CHANGE";
export const PROFILE_UPDATE_PENDING = "PROFILE_UPDATE_PENDING";
export const PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED";
export const PROFILE_FORM_RESET = "PROFILE_FORM_RESET";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED";

export const BACKGROUND_PICTURE_UPDATE_PENDING = "BACKGROUND_PICTURE_UPDATE_PENDING";
export const BACKGROUND_PICTURE_UPDATED = "BACKGROUND_PICTURE_UPDATED";
