export const INIT_STATE = "INIT_STATE";
export const ADD_TRIP_CHANGE = "ADD_TRIP_CHANGE";
export const ADD_TRIP_SUCCESS = "ADD_TRIP_SUCCESS";
export const ADD_TRIP_FAILED = "ADD_TRIP_FAILED";
export const ADD_TRIP_PENDING = "ADD_TRIP_PENDING";
export const ADD_TRIP_IMG_PREVIEW = "ADD_TRIP_IMG_PREVIEW";
export const ADD_TRIP_FORM_RESET = "ADD_TRIP_FORM_RESET";

export const UPDATE_TRIP_FORM_INIT = "UPDATE_TRIP_FORM_INIT";
export const UPDATE_TRIP_CHANGE = "UPDATE_TRIP_CHANGE";
export const UPDATE_TRIP_SUCCESS = "UPDATE_TRIP_SUCCESS";
export const UPDATE_TRIP_FAILED = "UPDATE_TRIP_FAILED";
export const UPDATE_TRIP_PENDING = "UPDATE_TRIP_PENDING";
export const UPDATE_TRIP_IMG_PREVIEW = "UPDATE_TRIP_IMG_PREVIEW";
export const UPDATE_TRIP_FORM_RESET = "UPDATE_TRIP_FORM_RESET";

export const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS";
export const DELETE_TRIP_PENDING = "DELETE_TRIP_PENDING";
export const DELETE_TRIP_FAILED = "DELETE_TRIP_FAILED";
export const REMOVE_TRIP_FROM_STATE = "REMOVE_TRIP_FROM_STATE";


export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";

export const PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED";

export const BACKGROUND_PICTURE_UPDATE_PENDING = "BACKGROUND_PICTURE_UPDATE_PENDING";

export const BACKGROUND_PICTURE_UPDATED = "BACKGROUND_PICTURE_UPDATED";